### ISSUE TITLE
Update FXdata : no work

### ISSUE THREAD

**Issue by nlmarcio** [Slluxx/fivem-servermanager#1]
Hello,
I have a problem when updating the FXdata.
It fails to retrieve the last file fx.tar.xz
And suddenly it returns an empty "fxdata" folder.

Can be missing something at the line: newestfxdata = "$ (curl $ masterfolder | grep '<a href' | tail -1 | awk -F[\> \ <]' {print $ 3} ')"

Thank you :)
*************************************************
Bonjour,
j'ai un probleme lors de la mise a jour du FXdata.
Il ne parvient pas a recuperer le dernier fichier fx.tar.xz
et du coup il renvoie un dossier "fxdata" vide.

peut etre manque t il quelque chose a la ligne : newestfxdata="$(curl $masterfolder | grep '<a href' | tail -1 | awk -F[\>\<] '{print $3}')"

Merci :)

**Comment by nlmarcio** [comment]
Desolate I realized that the error came from me.
I did not instal curl :/
Sorry!
*******************
Desole je me suis rendu compte que l'erreur venais de moi.
Je n'avais pas instaler curl :/
desole !

**Comment by Slluxx** [comment]
Updated the init script to also install / update wget and curl because of this.
#b4fd8dc
