### ISSUE TITLE
Automatic restart

### ISSUE THREAD

**Issue by tonny766** [Slluxx/fivem-servermanager#4]
Hello, possible to program automatic restart?

**Comment by Slluxx** [comment]
Automatic restarts are not usually not needed. Do you have a reason why i shall add that?

**Comment by tonny766** [comment]
hello, to clean the map, clear the cache to avoid errors, and apply the new updates.

**Comment by Slluxx** [comment]
updates are automatically applied by a server restart / resource refresh. The map will clean up after just a restart and int wont help you to avoid errors. either there are some or there arent.

clearing the cache manually is obsolete since the fx server exists.
